name: Validate PR

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para validar commits

      # 2. Validar nombre de la rama
      # Formato esperado: feature/..., bugfix/..., hotfix/...
      - name: Check Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          REGEX="^(feature|bugfix|hotfix|task)\/.*"
          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "Error: El nombre de la rama '$BRANCH_NAME' no sigue la convención (feature/..., bugfix/..., etc)."
            exit 1
          fi

      # 3. Validar formato de commits (Conventional Commits)
      - name: Check Commit Messages
        uses: wagoid/commitlint-github-action@v5

      # 4. Dockerfile y tamaño
      - name: Build multistage Docker image
        run: docker build -f Dockerfile -t app-multi:latest .

      - name: Show Docker image size
        run: |
          docker images app-multi:latest --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"
